# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  ligi.kernel_request_listener:
    class: Datenknoten\LigiBundle\EventListener\RequestListener
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: setLocale, priority: 18 }
