# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  ligi.kernel_request_listener:
    class: Datenknoten\LigiBundle\EventListener\RequestListener
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: setLocale, priority: 18 }
  ligi.twig_extension:
    class: Datenknoten\LigiBundle\Twig\LigiTwigExtension
    public: false
    tags:
      - { name: twig.extension }
  ligi.form.registration:
    class: Datenknoten\LigiBundle\Form\ProfileFormType
    tags:
      - { name: form.type, alias: ligi_user_profile }
  ligi.form.image:
    class: Datenknoten\LigiBundle\Form\ImageType
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: form.type, alias: ligi_image }